spring:
  profiles:
    active: dev # Activate spring dev profile
  h2:
    console: 
      enabled: true
      path: /console/
server: 
  port: 8080
logging:
  level:
    org.hibernate: DEBUG
    org.springframework: INFO
    com.mysmartfridge: DEBUG
security:
  basic:
    enabled: false
management:
  security: 
    enabled: false