spring:
  profiles:
    active: dev # Activate spring dev profile
  data:
    mongodb:
      database: mysmartfridge
      port: 0 # use a random free port for the embedded mongodb
server: 
  port: 8080
logging:
  level:
    org.hibernate: DEBUG
    org.springframework: INFO
    com.mysmartfridge: DEBUG
security:
  basic:
    enabled: false
management:
  security: 
    enabled: false