# Actuator configuration
management:
  context-path: /manage
endpoints: 
  shutdown:
    enabled: true
    sensitive: false
    
# deactivate hbm2ddl
spring:
  jpa:
    hibernate:
      ddl-auto: none
  